---
################################################################################
## Defaults file for ilmt_scanner.                                            ##
## All variables placed here can be overwritten.                               ##
################################################################################

lmt_local_file_storage_path: "./lmt_file_storage"
################################################################################
## Parameter        | lmt_local_file_storage_path
##==============================================================================
## Default Value    | "./lmt_file_storage"
## Possible Values  | Directory name (string)
##==============================================================================
## Description:
##   Path on a the control node where results packages from all the endpoints 
##   are stored. If not overwrite the default ./lmt_file_storage is used,
##   which is created as a subdirectory of a directory where playbooks
##   are located.
################################################################################

lmt_scanner_path_windows: "{{ ansible_env['ProgramFiles'] }}\\ibm\\LMTScanner"
################################################################################
## Parameter        | lmt_scanner_path_windows
##==============================================================================
## Default Value    | "{{ ansible_env['ProgramFiles'] }}\\ibm\\LMTScanner"
## Possible Values  | Directory name (string)
##==============================================================================
## Description:
##   Path on the Windows endpoints where scanner will be installed. 
################################################################################

# lmt_scanner_output_path_windows:
################################################################################
## Parameter        | lmt_scanner_output_path_windows
##==============================================================================
## Default Value    | "{{ lmt_scanner_path_windows }}/output"
## Possible Values  | Directory name (string)
##==============================================================================
## Description:
##   Path on the Windows endpoints where the scan results are generated by the 
##   scanner. 
################################################################################

lmt_scanner_path_unix: "/var/opt/ibm/LMTScanner"
################################################################################
## Parameter        | lmt_scanner_path_unix
##==============================================================================
## Default Value    | "/var/opt/ibm/LMTScanner"
## Possible Values  | Directory name (string)
##==============================================================================
## Description:
##   Path on the Unix/Linux endpoints where scanner will be installed. 
################################################################################

# lmt_scanner_output_path_unix:
################################################################################
## Parameter        | lmt_scanner_output_path_unix
##==============================================================================
## Default Value    | "{{ lmt_scanner_path_unix }}/output"
## Possible Values  | Directory name (string)
##==============================================================================
## Description:
##   Path on the Unix/Linux endpoints where the scan results are generated by  
##   the scanner. 
################################################################################

# lmt_server_path:
################################################################################
## Parameter        | lmt_server_path
##==============================================================================
## Default Value    | [Windows]    "{{ ansible_env['ProgramFiles'] }}\\ibm\\LMT"
##                  | [Linux/Unix] "/opt/ibm/LMT"
## Possible Values  | Directory name (string)
##==============================================================================
## Description:
##   Path to main directory of LMT Server on 'lmt_server' node.
################################################################################

lmt_server_port: 9081
################################################################################
## Parameter        | lmt_server_port
##==============================================================================
## Default Value    | 9081
##==============================================================================
## Description:
##   Port number of the License Metric Tool server. It is used to connect 
##   to the License Metric Tool server API while decommissioning computers.
################################################################################

# lmt_server_token:
################################################################################
## Parameter        | lmt_server_token
##==============================================================================
## Default Value    | Empty (none)
##==============================================================================
## Description:
##   API token of the License Metric Tool server.If the token is defined, 
##   the disconnected computer is automatically decommissioned from 
##   the License Metric Tool server during scanner uninstallation.
################################################################################

# lmt_server_datasource_path:
################################################################################
## Parameter        | lmt_server_datasource_path
##==============================================================================
## Default Value    | [Windows]    "{{ lmt_server_path }}\\datasource"
##                  | [Linux/Unix] "{{ lmt_server_path }}/datasource"
## Possible Values  | Directory name (string)
##==============================================================================
## Description:
##   Path to a disconnected datasource on 'lmt_server' node.
################################################################################

lmt_scanner_setup_timeout: 300
################################################################################
## Parameter        | lmt_scanner_setup_timeout
##==============================================================================
## Default Value    | 300
## Possible Values  | Number
##==============================================================================
## Description:
##   Number of seconds after which the scanner setup (and uninstaller) will be 
##   terminated reported as failed if not finish within defined period.
################################################################################


################################################################################
## Disconnected scanner setup specific settings below                         ##
## Following parameters are not relevant for collector playbook               ##
################################################################################

lmt_scanner_solaris_dsd_mode: false
################################################################################
## Parameter        | lmt_scanner_solaris_dsd_mode
##==============================================================================
## Corresponds to   | DSD_MODE env variable during disconnected scanner install
##==============================================================================
## Default Value    | false
## Possible Values  | true/false
##==============================================================================
## Description:
##   Information whether Solaris system is in the DSD domain, applicable only
##   for Solaris OS nodes.
################################################################################

#lmt_scanner_zlinux_machine_type:
#lmt_scanner_zlinux_processor_type:
#lmt_scanner_zlinux_shared_pool_capacity:
#lmt_scanner_zlinux_system_active_processors: 
################################################################################
## Description:
##   Set of parameters that describes underlying hardware of the System z host
##   on which ILMT zLinux scanner is going is to be installed that needs to be
##   defined in case when automatic capacity configuration is not supported.
##
##   Automatic capacity configuration is supported on Linux on z/KVM and on 
##   System z10 starting from model E64 (type 2097) mainframes with z/VM 6.3 
##   and later that supports the Store Hypervisor Information (STHYI) 
##   instruction.
##   Additionally, global performance data control option must be set in HMC for
##   LPARs for automatic capacity configuration to work.
##  
##   An example for z9 machine with 12 IFL processors running on a shared pool
##   with a capacity of 20, set the variables as follows:
##   lmt_scanner_zlinux_machine_type: "z9"
##   lmt_scanner_zlinux_processor_type: "IFL"
##   lmt_scanner_zlinux_shared_pool_capacity: "20"
##   lmt_scanner_zlinux_system_active_processors: "12"
################################################################################

lmt_scanner_software_scans_enabled: true
################################################################################
## Parameter        | lmt_scanner_software_scans_enabled
##==============================================================================
## Corresponds to   | SW_SCAN_SCHEDULE_ENABLED disconnected scanner parameter
##==============================================================================
## Default Value    | true
## Possible Values  | true/false
##==============================================================================
## Description:
##   Enables scheduling software scans in cron. If you set the value
##   of this parameter to TRUE, the first software scan is initiated after 
##   you setup the scanner. Subsequent scans run with the frequency that
##   is set in the lmt_scanner_software_scans_frequency parameter.
##   Software scan after each execution will automatically trigger pack results.
################################################################################

lmt_scanner_software_scans_frequency: "WEEKLY"
################################################################################
## Parameter        | lmt_scanner_software_scans_frequency
##==============================================================================
## Corresponds to   | SW_SCAN_FREQUENCY disconnected scanner parameter
##==============================================================================
## Default Value    | WEEKLY
## Possible Values  | DAILY/WEEKLY
##==============================================================================
## Description:
##   Defines the frequency of software scans, either daily or weekly.
################################################################################

# lmt_scanner_software_scan_day_of_week:
################################################################################
## Parameter        | lmt_scanner_software_scan_day_of_week
##==============================================================================
## Corresponds to   | SW_SCAN_DAY_OF_WEEK disconnected scanner parameter
##==============================================================================
## Default Value    | EMPTY
## Possible Values  | EMPTY/MON/TUE/WED/THU/FRI/SAT/SUN
##==============================================================================
## Description:
##   Defines the day of the week on which the weekly scan will run.
##   This parameter is relevant only if the lmt_scanner_software_scans_frequency 
##   parameter is set to WEEKLY. By default, this parameter is empty which means 
##   that the weekly scan will be scheduled starting from the time when the
##   install or upgrade or reconfigure playbook was run.
################################################################################

# lmt_scanner_software_scan_local_time:
################################################################################
## Parameter        | lmt_scanner_software_scan_local_time
##==============================================================================
## Corresponds to   | SW_SCAN_LOCAL_TIME disconnected scanner parameter
##==============================================================================
## Default Value    | EMPTY
## Possible Values  | EMPTY or time in the "HH:MM" format
##==============================================================================
## Description:
##   Defines the time (hour and minutes) during the day in the LOCAL time zone
##   of manage node when the scheduled software scan (weekly or daily) will run. 
##   By default, this parameter is empty which means that the scan will start at
##   the time of the day when the install or upgrade or reconfigure playbook was
##   run.
##
##   Example:
##   lmt_scanner_software_scan_local_time: "20:30"
##   Note: Ensure the time string is enclosed in quotation marks.    
################################################################################ 

lmt_scanner_daily_pack_results_enabled: true
################################################################################
## Parameter        | lmt_scanner_daily_pack_results_enabled
##==============================================================================
## Corresponds to   | DAILY_PACK_RESULTS_CREATION_ENABLED disconnected scanner 
##                  |   parameter
##==============================================================================
## Default Value    | true
## Possible Values  | true/false
##==============================================================================
## Description:
##   Enables scheduling of a daily output package creation.
##   If you set the value of this parameter to true, the first pack results 
##   is initiated 23 hours after you install the scanner. 
##   Subsequent packages will be generated with the daily frequency.
################################################################################

#lmt_scanner_public_cloud_type:
################################################################################
## Parameter        | lmt_scanner_public_cloud_type
##==============================================================================
## Corresponds to   | PUBLIC_CLOUD_TYPE disconnected scanner parameter
##==============================================================================
## Default Value    | Empty (none)
## Possible Values  | Name of a supported public cloud:
##                  |   "IBM Cloud Virtual Server"
##                  |   "IBM Power Virtual Server"
##                  |   "IBM SoftLayer"
##                  |   "IBM Cloud LinuxONE VS"
##                  |   "Microsoft Azure"
##                  |   "Amazon EC2"
##                  |   "Google Compute Engine"
##                  |   "Oracle Compute Instance"
##                  |   "Alibaba Elastic Compute Service"
##                  |   "Tencent Cloud Server Instance"
##                  |   "NEC Cloud IaaS Instance"
##                  |   "Fujitsu Cloud IaaS Instance"
##                  |   "NTT Enterprise Cloud Server"
##                  |   "NTT IaaS Powered by VMware"
##                  |   "NTT Data"
##                  |   "KDDI Virtual Server"
##==============================================================================
## Description:
##   Specifies the type of a public cloud on which the computer is running.
##   It allows for properly counting the number of Processor Value Units (PVUs)
##   per virtual core.
##
##   Example:
##   lmt_scanner_public_cloud_type: "Microsoft Azure"
##   Note: Ensure the name of the public cloud is enclosed in quotation marks.
##
##   For more information about supported types of public clouds, see:
##   https://ibm.biz/LMT_public_clouds_disconnected.
################################################################################

lmt_scanner_virt_host_scan_enabled: false
################################################################################
## Parameter        | lmt_scanner_virt_host_scan_enabled
##==============================================================================
## Corresponds to   | VIRTUALIZATION_HOST_SCAN_ENABLED disconnected scanner 
##                  | parameter
##==============================================================================
## Default Value    | false
## Possible Values  | true/false
##==============================================================================
## Description:
##   You can use this option only on Linux.   
##
##   Enables capacity scan on the virtualization host to retrieve capacity data
##   from all virtual machines that are managed by that host.
##
##   After this scan is enabled, it becomes a part of the regular capacity scan. 
##
##   Supported virtualization technologies:
##     * Xen on Linux x86
##     * KVM on Linux x86
##     * KVM on Power Linux
##
##   Prerequisites on the KVM host:
##     * Operating system: Linux x86 or ppc64
##     * Libvirt-client library installed on the host (virsh command available)
##       or xl command available
##     * Libxml2 library installed on the host (xmllint command available)
##     * Bash shell available
##
##   Prerequisites on the Xen host:
##     It is recommended to collect capacity data from Xen by using the
##     VM Manager Tool instead of setting this parameter. For more information,
##     see the product documentation.
################################################################################

lmt_scanner_collect_host_hostname: false
################################################################################
## Parameter        | lmt_scanner_collect_host_hostname
##==============================================================================
## Corresponds to   | COLLECT_HOST_HOSTNAME disconnected scanner parameter
##==============================================================================
## Default Value    | false
## Possible Values  | true/false
##==============================================================================
## Description:
##   Set the value of this parameter to TRUE to collect information about
##   host names of virtualization hosts during the virtualization host scan.
##   The lmt_scanner_virt_host_scan_enabled parameter must be set to TRUE before
##   you can enable collection of host names.
################################################################################

lmt_scanner_docker_scan_enabled: false
################################################################################
## Parameter        | lmt_scanner_docker_scan_enabled
##==============================================================================
## Corresponds to   | DOCKER_SCAN_ENABLED disconnected scanner parameter
##==============================================================================
## Default Value    | false
## Possible Values  | true/false
##==============================================================================
## Description:
##   This parameter only applies to machines with Linux operating system.
##   Set the value of this parameter to TRUE to enable the scan of all Docker 
##   containers that are deployed on the target managed node. 
################################################################################